version: '2'

services:
    kafka:
        image: spotify/kafka
        ports:
          - "2181:2181"
          - "9092:9092"
        environment:
          ADVERTISED_HOST: 127.0.0.1
          ADVERTISED_PORT: 9092
          NUM_PARTITIONS: 2
